### ISSUE TITLE
 DynamicServerError, from next.js 14.2.12

### ISSUE THREAD

**Issue by BowlingX** [Xunnamius/next-test-api-route-handler#1078]
<details open><summary><strong>The problem</strong></summary>

Tests stopped working after upgrading to next.js `14.2.12` (worked with `14.2.11`)

The tests are testing an `appHandler`.

</details>

<details><summary><strong>Reproduction steps</strong></summary>

Update to next.js `14.2.12`

</details>

<details open><summary><strong>Additional context</strong></summary>

Relevant log lines:
```
 DynamicServerError: Dynamic server usage: Route is configured with methods that cannot be statically generated.
          at /***/node_modules/next/src/server/future/route-modules/app-route/module.ts:296:33
          at AsyncLocalStorage.run (node:async_hooks:346:14)
          at Object.run [as wrap] (/.../node_modules/next/src/server/async-storage/static-generation-async-storage-wrapper.ts:106:20)
          at wrap (/***/node_modules/next/src/server/future/route-modules/app-route/module.ts:285:49)
          at AsyncLocalStorage.run (node:async_hooks:346:14)
          at Object.run [as wrap] (/.../node_modules/next/src/server/async-storage/request-async-storage-wrapper.ts:171:20)
          at wrap (/***/node_modules/next/src/server/future/route-modules/app-route/module.ts:281:36)
          at AsyncLocalStorage.run (node:async_hooks:346:14)
          at AppRouteRouteModule.run [as execute] (/.../node_modules/next/src/server/future/route-modules/app-route/module.ts:275:61)
          at AppRouteRouteModule.execute [as handle] (/.../node_modules/next/src/server/future/route-modules/app-route/module.ts:476:35)
          at /.../node_modules/next-test-api-route-handler/dist/src/index.js:231:49 {
        description: 'Route is configured with methods that cannot be statically generated.',
        digest: 'DYNAMIC_SERVER_USAGE'
      }
```

</details>

**Comment by BowlingX** [comment]
Potentially related to https://github.com/Xunnamius/next-test-api-route-handler/issues/1076. I tried the latest version, but the issue persists

**Comment by BowlingX** [comment]
The solution is actually quite easy, the option name changed:

https://github.com/Xunnamius/next-test-api-route-handler/blob/main/src/index.ts#L517C17-L517C36, see https://github.com/vercel/next.js/compare/v14.2.11...v14.2.12#diff-fc60fd1422337f4ef0f858c509b2aee63bd9919b4fbc911fb793af3ae21472d6R272

So setting

```ts
supportsDynamicResponse: true,
```

works
