### ISSUE TITLE
Jest did not exit one second after the test run has completed.

### ISSUE THREAD

**Issue by scottsymm** [Xunnamius/next-test-api-route-handler#962]
i am looking for a nice way to unit test my route handlers.
many thanks for this package.

when using the appHandler, there seems to be an open promise after my tests complete: `Jest did not exit one second after the test run has completed.`

is this expected behavior, or am i perhaps missing some sort of tear down call ?

## Jest --detectOpenHandles
```
  ●  TCPWRAP

      4 | describe('POST() route', () => {
      5 |   it('FOO', async () => {
    > 6 |     await testApiHandler({
        |                         ^
      7 |       appHandler,
      8 |       async test({ fetch }) {
      9 |         const result = await fetch({ method: 'POST', body: 'dummy-data' });

      at port (../../node_modules/.pnpm/next-test-api-route-handler@4.0.0_next@14.0.2/node_modules/next-test-api-route-handler/dist/src/index.js:121:15)
      at testApiHandler (../../node_modules/.pnpm/next-test-api-route-handler@4.0.0_next@14.0.2/node_modules/next-test-api-route-handler/dist/src/index.js:120:24)
      at Object.<anonymous> (app/match/organizations/_tests/POST.route.test.ts:6:25)
```

## My route and test
```
import { NextRequest, NextResponse } from 'next/server';
export async function POST(request: NextRequest) {
  return NextResponse.json({
    received: true,
  });
```
```
import { testApiHandler } from 'next-test-api-route-handler';
import * as appHandler from '../route';

describe('POST() route', () => {
  it('test()', async () => {
    await testApiHandler({
      appHandler,
      async test({ fetch }) {
        const result = await fetch({ method: 'POST', body: 'foo' });
        await expect(result.json()).resolves.toStrictEqual({ received: true });
      },
    });
  });
});
```

## Steps To Reproduce using next-test-api-route-handler repo
* it *seems* like the repo unit tests also demonstrate it
```
next-test-api-route-handler on  main is 📦 4.0.2 via ⬢ v18.17.1 took 24.8s 
➜ npm test

> next-test-api-route-handler@4.0.2 test
> npm run test:unit --


> next-test-api-route-handler@4.0.2 test:unit
> NODE_OPTIONS='--no-warnings' NODE_ENV=test jest '/unit-.*\.test\.tsx?' --testPathIgnorePatterns '/dist/'

 PASS  test/unit-index-imports.test.ts
 PASS  test/unit-msw.test.ts
 PASS  test/unit-external.test.ts
 PASS  test/unit-index.test.ts
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.

Test Suites: 4 passed, 4 total
Tests:       93 passed, 93 total
Snapshots:   0 total
Time:        1.821 s
Ran all test suites matching /\/unit-.*\.test\.tsx?/i.
```

**Comment by Xunnamius** [comment]
Thanks for this detailed report! I knew there'd be some cases I was overlooking. I'll investigate tonight

**Comment by Xunnamius** [comment]
Turns out later versions of Node terminate persistent server connections more optimally than Node@18 does. Explicitly calling [`server.closeAllConnections()`](https://nodejs.org/docs/latest-v18.x/api/http.html#servercloseallconnections) after calling [`server.close()`](https://nodejs.org/docs/latest-v18.x/api/http.html#serverclosecallback) did the trick.

Thanks again for opening this issue, I learned from fixing this.
